server:
  port: 8888

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    resources:static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.5.233:53306/xlauch-tadmin?useUnicode=true&useSSL=false&characterEncoding=utf-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: xlauch
    password: Xlauch@root
    # Oracle
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: maku_generator
#    password: maku_generator
    # SQLServer
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=maku_generator;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: 123456@maku
    # postgresql
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
    # 达梦8
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://localhost:5236/maku_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: maku_generator
#    password: 12345678


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.xlauch.generator.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
